### ISSUE TITLE
add new 

### ISSUE THREAD

**Issue by Daniel3356** [7c/fakefilter#105]
from https://tempail.com/ 
add gufum.com

from https://anonymmail.net/
add : 
cplusa.net
usatron.net
luckyemail.net
wunn.edu.pl

**Comment by Daniel3356** [comment]
add Also : riseist.com , asifmail.com, smmly.co, aiwriter.live from https://faxmail.co/

**Comment by 7c** [comment]
https://github.com/7c/fakefilter/blob/main/CHARTS.md#tempailcom

- anonymmail.net : added to automation
- faxmail.co: added to automation
- mxscoout.com added under static list we introduced recently.
