### ISSUE TITLE
HTML fragments in fakemailgenerator.com entries

### ISSUE THREAD

**Issue by bradleyjkemp** [7c/fakefilter#11]
Hey, there seems to be some problem with the extraction from fakemailgenerator.com. Seems it's pulling in some HTML fragments rather than domain names.

You can see the bad entries here: https://github.com/7c/fakefilter/blob/f99596ce05bb67eaef3611cce9b56dfc90c5a89c/txt/data.txt#L1531-L1542

(discovered because [my Go wrapper](https://github.com/bradleyjkemp/fakefilter-go) started getting compile failures)

**Comment by 7c** [comment]
thanks! working on it.
