### ISSUE TITLE
mail1.io

### ISSUE THREAD

**Issue by robwoodgate** [7c/fakefilter#110]
Temp mail provider by def24, has a selector for their hostnames on the main page.

Current DEA domains include:

basketball.group
britishpreschool.net
busykitchen.coms
hacker9.org
l9pdev.com
linux0.net
ucm8.com
looksecure.net
mail1.local
megaradical.com
multiscanner.org
pimmel.top
privacylock.net

**Comment by 7c** [comment]
thanks, added as 'mail1.io'
