### ISSUE TITLE
instantmail.buzz

### ISSUE THREAD

**Issue by 3HeadedApe** [7c/fakefilter#15]
According to google (aka blind first hit) it's from instant-email.org which I see _is already_ in the database, but only covers:

    2mailfree.shop
    dummymails.cc
    freakmails.club
    free2mail.xyz
    mailboxmaster.info
    mailsugo.buzz
    man2man.xyz
    molman.top

So not sure if instantmail.buzz should be in _this_ list, connected to instant-email.org or not.

**Comment by 7c** [comment]
Based on my research `instantmail.buzz` does not really belong to them or not mapped to their smtp... it has different properties than the ones we have detected. Once they put new domains, we will detect them
