### ISSUE TITLE
data.txt is missing info

### ISSUE THREAD

**Issue by d3xt3r01** [7c/fakefilter#19]
I don't see "grandeikk.com" under the "emailondeck.com" provider or "shbiso.com" under "temp-mail.org"
Both have been available for a few days.
Both do show up when using the api though

**Comment by 7c** [comment]
Thanks, this is because they have been harvested today. They will be available tomorrow at the Repo. We push every 24h to the repo but API is live.

**Comment by d3xt3r01** [comment]
Is there anything I can help with for harvesting? I do have a few servers
that could run some docker stuff to help if needed...

**Comment by 7c** [comment]
Your help, in submitting issues is greatly appreciated. We do have enough resources for 300 more providers for sure.

**Comment by d3xt3r01** [comment]
Great, as long as they don't get blocked and have enough cross-geo variety...!
