### ISSUE TITLE
Find a way to detect temp-mail.org email with the same pattern

### ISSUE THREAD

**Issue by DanielAbsi** [7c/fakefilter#2]
I find a way to detect potential disposable email from temp-mail.org by filtering them.
All temp-mail.org email have the same pattern and if the pattern is found manual detection is easier to detecting them:

All temp-mail.org email is a .com domain name.
All temp-mail.org the Registrar is NameSilo, LLC.
All temp-mail.org is Registered On 2018-01-31, Updated On 2022-03-03 and Expires On 2023-01-31.
All temp-mail.org use the Name Server (NS): NS1.DNSOWL.COM
All temp-mail.org have setup a DMARC Record with this exact signature:
`v=DMARC1; p=reject; rua=mailto:reporterdmarc@yandex.ru; ruf=mailto:reporterdmarc@yandex.ru; rf=afrf; sp=reject; fo=1; pct=100; ri=604800; adkim=s; aspf=s`

**Comment by 7c** [comment]
Thanks for this guide @DanielAbsi - we are testing our latest tool now, it seems to work. We will support temp-mail and 8 other hardened providers next week or sooner.

**Comment by 7c** [comment]
https://github.com/7c/fakefilter/commit/4c2682429b0cf86de0dfe21cb896013a5de8fda7

started to detect 6 protected providers, we will beta test next days but we have launched this patch now..

**Comment by DanielAbsi** [comment]
Have you made it temp-mail.org email detector?

**Comment by 7c** [comment]
Sure; look at [https://github.com/7c/fakefilter/blob/main/CHARTS.md#temp-mailorg](chart) and [https://github.com/7c/fakefilter/blob/main/markdown/README.md#temp-mailorg](results) please
