### ISSUE TITLE
new to add

### ISSUE THREAD

**Issue by DanielAbsi** [7c/fakefilter#23]
## From gettempmail.com

add: mailboxhub.site

## From: onetempmail.com
add: emailtoshare.com
add: emailly.co
add: getmail.pics
add: mailhq.club
add: meetmail.me
add: openmail.lol
add: usemail.live
add: usemail.xyz

## From tempmail.altmails.com
add: altmails.com

## From smailpro.com
add: donymails.com

## From burnermail.io
add: nicoric.com

**Comment by DanielAbsi** [comment]
Can you please update the list.

**Comment by 7c** [comment]
Thanks @DanielAbsi , onetempmail.com added for automatic detection, tempmail.altmails.com added for automatic detection.

We do not support `burnermail.io` for now, because this is browser extension only provider
smailpro.com seems to be down

thanks for your contribution.
