### ISSUE TITLE
katamo1.com and wiicheat.com

### ISSUE THREAD

**Issue by pierrocknroll** [7c/fakefilter#33]
Hi,
We have recently had fake users from these domains: 
`katamo1.com` and `wiicheat.com`
Could you look into whether they should be added to your list? I have seen these domains in other blacklists.
Thanks

**Comment by 7c** [comment]
Thanks for contribution, we do scan providers main websites automatically.... If you know the provider, we will be happy to add watch for this new provider. We cannot add domains without knowing the provider at this concept
