### ISSUE TITLE
tempmail.plus domains

### ISSUE THREAD

**Issue by matuspavliscak** [7c/fakefilter#34]
Can you please add following domains from tempmail.plus? Thanks!

- mailto.plus
- fexpost.com
- fexbox.org
- mailbox.in.ua
- rover.info
- inpwa.com
- intopwa.com
- tofeat.com
- chitthi.in

**Comment by 7c** [comment]
thanks for this new provider, we have added a worker to watch this provider. FakeFilter automatically fetches their domains. Those domains should be in our database tomorrow.
