### ISSUE TITLE
trash-mail.com is missing o_O

### ISSUE THREAD

**Issue by chrisLovesCode** [7c/fakefilter#35]
hi 
trash-mail.com need to be added. it already is there as provider for various domains like opentrash.com , but you can choose on their website the main domain to!
maybe it should be considered to blacklist all provider domains by default?

**Comment by chrisLovesCode** [comment]
also add trashmail.com ..

**Comment by 7c** [comment]
> also add trashmail.com .. there it's the same, its already a provider for trashmail.fr but the provider mail is not black listed, which is choosable to for creating fake mails https://fakefilter.net/api/is/fakedomain/trashmail.fr vs https://fakefilter.net/api/is/fakedomain/trashmail.com why not blacklist providers by default?

thanks, we do use automatic methods to harvest domains, for us the trashmail.com is not being used for creating fake emails for now. Do you have any indication?

**Comment by 7c** [comment]
> also add trashmail.com .. there it's the same, its already a provider for trashmail.fr but the provider mail is not black listed, which is choosable to for creating fake mails https://fakefilter.net/api/is/fakedomain/trashmail.fr vs https://fakefilter.net/api/is/fakedomain/trashmail.com why not blacklist providers by default?

https://fakefilter.net/api/is/fakedomain/trash-mail.com

thanks
