### ISSUE TITLE
add edumail.icu

### ISSUE THREAD

**Issue by makuga01** [7c/fakefilter#36]
Could you please add following domains from edumail.icu

e-mail.edu.pl
unip.edu.pl
edumail.icu
meda.email
linux-mail.xyz
mailtrail.xyz
notamail.xyz
write-me.xyz
text-me.xyz
sharkmail.xyz
mailsnail.xyz

**Comment by 7c** [comment]
Thanks, we have added this provider edumail.icu to be watched in the future automatically. It will appear tomorrow in our database.
