### ISSUE TITLE
temp-mail.org updates working?

### ISSUE THREAD

**Issue by gingerlime** [7c/fakefilter#39]
Thanks for maintaining fakefilter. I was keeping an eye on temp-mail.org in the last couple of days, and it looks like the cycled through new domains a day or so ago. However, it doesn't look like the latest update ~1h ago picked up those new domains?

The domains I can see on temp-mail.org at the moment:

```
themesw.com
tingn.com
tohup.com
unicsite.com
usharer.com
v3dev.com
vingood.com
webonoid.com
```

The previous "batch" of domains included:

```
chnlog.com
cmeinbox.com
cnxcoin.com
dentaltz.com
dewareff.com
kaftee.com
letpays.com
prolug.com
```

and those are reflected on fakefilter, but not the newer batch. Except `tingn.com`. So perhaps your monitoring code just runs once and captures one new domain? however I think temp-mail.org randomizes their domains and seem to (at least at the moment) use 8 different domains per batch.

I imagine your process/code for scanning disposable providers is private for security reasons (not make it too easy for disposable providers to break your monitoring), but I just wanted you to be aware. Happy to collaborate on the monitoring side of things if it helps :)

**Comment by 7c** [comment]
Thanks for your contribution; this is important to us. I have noticed that 3 of the 'new' batch is included in the meantime. Yes, this provider is not easy like the others and we cannot scan them too many times/day. So it will probably take time until we have all their new domains. Let's watch it, please. Speed is probably important we will be working on those cases too in near future.

**Comment by 7c** [comment]
Obviously temp-mail.org and 10minemail.com are somehow linked together. Our system has captures all mentioned domains in one or the other provider successfully. It sometimes takes time, especially if they randomize.

**Comment by gingerlime** [comment]
Thank you @7c. Yeah, definitely. And at least from what I observed, temp-mail.org randomizes the domains and seem to use ~8 domains at any given time, and they swap them from time to time. I just observed when they changed the domains, and the list wasn't up-to-date yet. It takes a couple of days I guess :) Is there any way to update the list more frequently? or do you accept "contributions" if someone runs their own provider scans and pushes updates to this repo? just an idea ;-)

**Comment by 7c** [comment]
Thanks @gingerlime - we will think how we can make things faster... We intend to keep everything fully automated, otherwise we will end up within a garbage of domains like many other lists out there. Their main problem is the clutter and history. We really want to make this better.

**Comment by gingerlime** [comment]
Yes, I completely agree. That's why I thought about adding more provider scanners or updating even more frequently would be useful. I think manually submitting domains is not effective enough when some providers cycle through domains quickly. It's going to be a constant cat and mouse game though I guess.

https://github.com/disposable/disposable seem to do a good job aggregating several sources, and they also do MX record checks, so you can get a list of disposable domains that are actually active now. They also use fakefilter as one of the data sources and that's how I found you :)
