### ISSUE TITLE
add new disposable email from emailondeck.com

### ISSUE THREAD

**Issue by DanielAbsi** [7c/fakefilter#4]
@glsupposek.com

**Comment by DanielAbsi** [comment]
add `##burnermail.io
nicoric.com`

**Comment by 7c** [comment]
Thanks @DanielAbsi glsupposek.com was discovered today afternoon from our system, it will be added to the list by next update (which is 00:00 GMT)

**Comment by 7c** [comment]
For now we do not support burnermail.io because they do require signup and/or are browser extension... our automatic system does not have a module for that (for now at least, since their impact is low, it is like 1/20 of temp-mail.org)
