### ISSUE TITLE
FakeFilter API doesn't check for subdomain

### ISSUE THREAD

**Issue by imCorfitz** [7c/fakefilter#44]
I use this quick helper function in my app to first check if I can validate the email using the always-updated API and then fallback to my local package:

```ts
import { isFakeEmailOnline, isFakeEmail as isFakeEmailLocal } from 'fakefilter';

export default async function isFakeEmail(email: string) {
	const onlineResponse = await isFakeEmailOnline(email);
	console.log('local:', isFakeEmailLocal(email));
	if (onlineResponse === null) {
		return !!isFakeEmailLocal(email);
	}
	console.log('response:', onlineResponse);
	return !!onlineResponse.isFakeDomain;
}
```

And this is the response in the console:

```bash
7:49:49 AM [vite] page reload src/lib/server/utils/isFakeEmail.ts (x4)
7:49:49 AM [vite-plugin-svelte] ssr compile done.
package files    time     avg
my-app      1   1.6ms   1.6ms
# Here I check email ztmowxbncjifaksvtm@tpwlb.com
local: tpwlb.com
response: {
  retcode: 200,
  isFakeDomain: 'tpwlb.com',
  details: {
    provider: '10minutemail.com',
    firstseen: 1676090000,
    lastseen: 1676920000,
    randomSubdomain: false
  }
}
# Here I check email ztmowxbncjifaksvtm@sub.tpwlb.com <-- notice "sub" in domain
local: tpwlb.com
response: { retcode: 200, isFakeDomain: false, details: null }
```

The online response is correct when simply using the normal (fake) email address `ztmowxbncjifaksvtm@tpwlb.com` but if I add a subdomain to the email address only my local response is correct.

Now - granted it doesn't affect my app, as I doubt many of these providers are using subdomains anyway, and thus they will never receive the verification email in order to gain access, but I wanted to flag this for a future update to the API.

**Comment by 7c** [comment]
https://github.com/7c/fakefilter/issues/46
