### ISSUE TITLE
New to the list

### ISSUE THREAD

**Issue by DanielAbsi** [7c/fakefilter#5]
ADD: 
from : https://default.tmail.thehp.in/mailbox
a.zeemail.xyz

And add: 
from https://demo.lobage.com/trashmails/en
trashmails.xyz

**Comment by 7c** [comment]
Thanks @DanielAbsi - the lobage.com seems not to work and it seems to be the demo of [this software which can be purchased](https://codecanyon.net/item/trash-mails-temporary-email-address-system/33734549?irgwc=1&clickid=3oDUZWTDUxyIWQR2vPRMTyK6UkGVGbQ1rTyV140&iradid=275988&irpid=2379037&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=)

thehp.in - we will add to our system, thanks

**Comment by DanielAbsi** [comment]
> Thanks @DanielAbsi - the lobage.com seems not to work and it seems to be the demo of [this software which can be purchased](https://codecanyon.net/item/trash-mails-temporary-email-address-system/33734549?irgwc=1&clickid=3oDUZWTDUxyIWQR2vPRMTyK6UkGVGbQ1rTyV140&iradid=275988&irpid=2379037&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=)
> 
> thehp.in - we will add to our system, thanks

it's still a disposable. some people use it becuase they know that it's for demo and not for disposable. people are looking for not detected solutions.

**Comment by 7c** [comment]
@DanielAbsi - this domain `trashmails.xyz` seems not to be hosted there... We do not want to add domains separate from providers. Have you tried it? This service looks like a demo and the income does not work. One theory is that this domain `trashmails.xyz` is used from different provider we do not know the url

**Comment by 7c** [comment]
`default.tmail.thehp.in` has been added to the system, we automatically detect new domains (if any)

**Comment by DanielAbsi** [comment]
Now from the with the same interface: minutemailbox.com 
add freemailus.com
