### ISSUE TITLE
Add domains

### ISSUE THREAD

**Issue by uhlhosting** [7c/fakefilter#50]
155mail.ru
inbox.lv
inbox.ru
mail.imailfree.cc
mail.ru
mail.rub
mailbox.imailfree.cc

**Comment by 7c** [comment]
Thanks for your submission.. We do not add domains manually, because we aim consistency and relevancy. Unless we see a disposable email service, we cannot add them manually. If you see them somewhere used, please contact us, so the service can be added to fakefilter.

**Comment by uhlhosting** [comment]
These domains are used in spam registrations in wordpress and woocommerce, i would not had them mentioned otherwise.
