### ISSUE TITLE
Random subdomain

### ISSUE THREAD

**Issue by StanislavPrusac** [7c/fakefilter#53]
Anonbox  says on its website ( https://anonbox.net ) :
> anonbox creates virtual Mailboxes consisting of two parts: a random email address and a random mailbox name, for example
> uuuuuuuuuuuu@dddddddddddd.anonbox.net
> https://anonbox.net/dddddddddddd/mmmmmmmmmmmm/
> where d simply is a hash of date, u and m are completely random.

Since the subdomain is random, I don't think it makes sense to add a fully qualified domain name (FQDN), for example:
5yg2o.anonbox.net, lhl4c.anonbox.net, ...
because "5yg2o" (third level domain) is a "hash of the date".

That's why I think that in JSON "Offline Formats" should only be put Second-level domain + TLD, more precisely, subdomain of public suffix domain (PSD)

Example1: 5yg2o.anonbox.net
FQDN = 5yg2o.anonbox.net
Subdomain of PSD = anonbox.net
TLD = PSD = net

Example2: 5yg2o.example.co.uk
FQDN = 5yg2o.example.co.uk
Subdomain of PSD = example.co.uk
PSD = co.uk
TLD = uk

PSD can be obtained here https://publicsuffix.org/ and for the implementation of domain parsing to obtain subdomain of PSD one of the libraries listed here can be used, depending on which programming language you need: https://publicsuffix.org/learn/

In this way, all cases will be covered, not only with anonbox.net, but possibly also with others who have such a practice of having a random third level domain (3LD)  if the email is validated on subdomain of PSD and not on FQDN

This requires that a developer, who wants to validate an email if it is DEA, using this list must also parse the email, i.e. from the FQDN part of the email, get the subdomain of PSD part by parsing and check for it, if it is on your list.

Workaround for me, for now is that I parse all domains from your JSON and extract subdomain of PSD and validate the email on it, which also parses it to get subdomain of PSD from it.

Links:
https://en.wikipedia.org/wiki/Second-level_domain
https://en.wikipedia.org/wiki/Fully_qualified_domain_name
https://en.wikipedia.org/wiki/Public_Suffix_List
https://en.wikipedia.org/wiki/Domain_name

**Comment by 7c** [comment]
This was covered with latest patches
