### ISSUE TITLE
add internetkeno.com

### ISSUE THREAD

**Issue by dvarchev** [7c/fakefilter#54]

**Comment by dvarchev** [comment]
I'm not quite sure what you refer to as "service behind" but We encounter fake user registrations and service abuse by ppl using this domain. It is also included in other lists of disposable email addresses - i.e. https://github.com/disposable/disposable-email-domains

**Comment by dvarchev** [comment]
You can create a temp email for that domain from https://mail.tm/en/ if that's what you were looking for.

**Comment by 7c** [comment]
Thanks! mail.tm has been fixed. This domain is part of our repo.
