### ISSUE TITLE
add domains

### ISSUE THREAD

**Issue by sobolevdmitry** [7c/fakefilter#57]
Unfortunately, I do not know what service they are from, but I have experienced many registrations from these domains:

```
onlcool.com
mixinghphw.com
```

If I believe the verifymail.io (https://verifymail.io/domain/mixinghphw.com), they are from `temp-mail.org`

**Comment by 7c** [comment]
![image](https://github.com/7c/fakefilter/assets/22910022/893e2f23-8f84-43de-b303-bc8d1693cae1)

As you know fakefilter automates things, we have captures the seconddomain already by one of our watched providers... About the first one we really have to look. We do not add domains manually. We watch providers and remove them automatically after 1 year and wait until they enter our loop again.
