### ISSUE TITLE
please remove cloudflare.com

### ISSUE THREAD

**Issue by celso** [7c/fakefilter#71]
Hi,

Looks like cloudflare.com is listed as a fake/disposable email provider in your list, causing issues delivering email to some of our partners that use fakefilter. I have no idea why we got listed here, but the cloudflare.com domain is exclusively used for corporate email and employees. Can you help us get removed from the list?

**Comment by 7c** [comment]
{"retcode":200,"isFakeDomain":"cloudflare.com","details":{"providers":["txen.de"],"hosts":{"cloudflare.com":{"firstseen":1684370000,"lastseen":1684370000}}}}

sorry for this, i have just added cloudflare.com into whitelist, will be released within minutes. Thanks!
