### ISSUE TITLE
New temp service add to the blacklist.

### ISSUE THREAD

**Issue by arthkk** [7c/fakefilter#75]
I didn't find getnada.cc in your database. It's a new temp mail service. Please add it to the blacklist.

**Comment by GalacticHypernova** [comment]
Here's the API for it:
https://getnada.cc/api/domains/GwNvKEofrdyS7JTXCzHQ
Returns the available domains:
![image](https://github.com/7c/fakefilter/assets/92037085/09f2980b-03d2-49cc-b273-d630a831db73)

**Comment by 7c** [comment]
Thanks! we added them.
