### ISSUE TITLE
please add "temporary-email.org", "internxt.com"

### ISSUE THREAD

**Issue by dibyendu2280** [7c/fakefilter#79]
please add "temporary-email.org", "internxt.com"

**Comment by 7c** [comment]
Thanks! added temporary-email.org only. I dont see reason for internxt.com to be true.

**Comment by Daniel3356** [comment]
Hey Also from https://internxt.com/temporary-email
add crankymonkey.info

**Comment by dibyendu2280** [comment]
please add 10minute-email.com

**Comment by 7c** [comment]
> @7c `internxt.com`
> 
> https://internxt.com/temporary-email

added to automation
