### ISSUE TITLE
Add Inst Mail addr

### ISSUE THREAD

**Issue by getglobal23** [7c/fakefilter#80]
Instmail addr is an app and the chrome extension 

bangban.uk
catgroup.uk
goatmail.uk
sendnow.win
ccmail.uk
exdonuts.com
hamham.uk
digdig.org
owleyes.ch
stayhome.li
fanclub.pm
hotsoup.be
simaenaga.com
tapi.re
fuwari.be
magim.be
mirai.re
moimoi.re
heisei.be
honeys.be
mbox.re
uma3.be
instaddr.ch
quicksend.ch
instaddr.win
instaddr.uk
meruado.uk
nekosan.uk
fuwa.li
kpost.be
wanko.be
fuwa.be
usako.net
eay.jp
via.tokyo.jp
ichigo.me
choco.la
cream.pink
svk.jp
f5.si
macr2.com
ruru.be
neko2.net
fuwamofu.com
merry.pink

**Comment by 7c** [comment]
Thanks,  we have added this as provider!

**Comment by getglobal23** [comment]
When this will reflect on the data.txt file ?

**Comment by 7c** [comment]
They are slowly being [crawled](https://github.com/7c/fakefilter/blob/main/markdown/README.md#kukulu). Unfortunately we cannot insert manual domains inside our automated system. This provider will soon be crawled fully and all future domains will be part of json/txt/markdown/api
