### ISSUE TITLE
Add new disposable domain

### ISSUE THREAD

**Issue by ghost** [7c/fakefilter#85]
Provider is https://skiff.com/quick-alias and it's actually subdomains, each user can generate their own subdomain. I tested it, very easy.

The page title of https://skiff.com/quick-alias is "Quick alias burner email address". In the HTML I see

```
<meta name="description" content="Secure and quick-to-create burner email addresses with Skiff!
```
There is a browser plugin https://github.com/irazasyed/email-masker to create one email per website, skiff.com's twitter account promoted it, the github repository is tagged as 'burner-email'

You should add:

- `maskmy.id` because it is there main domain
- `anything.maskmy.id` because it allows you to create disposable addresses with random subdomains
![IMG_1500](https://github.com/7c/fakefilter/assets/153675616/ed76e1cc-0662-4c47-9633-c3ea618e0741)
![IMG_1501](https://github.com/7c/fakefilter/assets/153675616/83576fdc-377f-4ad1-b5d3-3429fc560d04)

**Comment by Hvkgtdhjgug** [comment]
@7c

**Comment by mtmail** [comment]
This user copied my research, report and screenshot from https://github.com/wesbos/burner-email-providers/pull/427 I'm not affiliated and don't know their intentions.

**Comment by Hchchg** [comment]
Also 

```
mailbox.zip
sailmail.io
```

![IMG_1719](https://github.com/7c/fakefilter/assets/155533164/439c13d2-d1f5-47e3-a1b9-3dcdbb82352a)

@mtmail @7c

**Comment by GalacticHypernova** [comment]
This is also a domain which I suggested to add back in #73, so seeing another person suggest to add it is very comforting

**Comment by mtmail** [comment]
The company was acquired by Notion. The service will be discontinued soon https://www.notion.so/blog/meet-skiff-the-newest-member-of-the-notion-family

**Comment by 7c** [comment]
thanks, i confirm, they are now part of notion, we will be watching...
