### ISSUE TITLE
muellmail.com

### ISSUE THREAD

**Issue by elmolm** [7c/fakefilter#87]
List of their domains:

- 10minmail.de
- 10minutenmail.xyz
- existiert.net
- fliegender.fish
- jaga.email
- mdz.email
- muellmail.com
- muellemail.com
- muell.monster
- muell.icu
- muell.xyz
- muell.io
- magspam.net
- fukaru.com
- oida.icu
- papierkorb.me
- spam.care
- ultra.fyi
- tonne.to
- wegwerfemail.de
- dsgvo.party
- knickerbockerban.de
- lambsauce.de
- ramenmail.de
- ji5.de
- ji6.de
- ji7.de
- sudern.de

![Xnip2024-01-17_11-23-48](https://github.com/7c/fakefilter/assets/1143569/81215345-8b86-4825-85ab-2a41c75677fa)

**Comment by 7c** [comment]
thanks, added/fixed the automation, they had new design
